# Generated by Django 2.2.16 on 2023-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('tmc', models.CharField(max_length=150, verbose_name='ТМЦ')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('note', models.CharField(max_length=1024, verbose_name='Примечание')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('change_date', models.DateTimeField(verbose_name='Дата изменения')),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('review_date', models.DateTimeField(verbose_name='Дата ревизии')),
                ('category', models.ForeignKey(on_delete='Категория', to='reg.Categoryes')),
                ('manufacturer', models.ForeignKey(on_delete='Производитель', to='reg.Manufacturers')),
            ],
        ),
    ]
