# Generated by Django 2.2.16 on 2023-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_auto_20230505_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartsevents',
            name='table_name',
        ),
        migrations.AlterField(
            model_name='categoryes',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
    ]
