# Generated by Django 2.2.16 on 2023-05-05 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0007_auto_20230505_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SparePartsEvents',
            new_name='CategoryesEvents',
        ),
    ]
