# Generated by Django 2.2.16 on 2023-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_auto_20230505_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryesevents',
            name='data',
            field=models.TextField(default='', verbose_name='Данные'),
        ),
    ]
