# Generated by Django 2.2.16 on 2023-07-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_categoryesevents_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='review_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата ревизии'),
        ),
    ]
